

#ifndef _PALETTE_H_
#define _PALETTE_H_




#ifdef RGB
#undef RGB
#endif
#define RGB(r,g,b)				(((r)<<16)|((g)<<8)|(b))

// LFRM_BPP_16 - RGB 565
#define RGB_16_RED				0xF800
#define RGB_16_GREEN			0x07E0
#define RGB_16_BLUE				0x001F	
#define RGB_16_WHITE			(RGB_16_RED|RGB_16_GREEN|RGB_16_BLUE)
#define RGB_16_BLACK			0x0000
#define RGB_16_MAGENTA			(RGB_16_RED|RGB_16_BLUE)
#define RGB_16_YELLOW			(RGB_16_RED|RGB_16_GREEN)
#define RGB_16_CYAN				(RGB_16_GREEN|RGB_16_BLUE)


#define COLOUR_RED				RGB_16_RED
#define COLOUR_GREEN			RGB_16_GREEN
#define COLOUR_BLUE				RGB_16_BLUE
#define COLOUR_WHITE			RGB_16_WHITE
#define COLOUR_BLACK			RGB_16_BLACK
#define COLOUR_MAGENTA			RGB_16_MAGENTA
#define COLOUR_YELLOW			RGB_16_YELLOW
#define COLOUR_CYAN				RGB_16_CYAN

#ifndef COLOUR_24TO16
#define COLOUR_24TO16(c)		((((c>>16)&0xF8)<<8) | (((c>>8)&0xFC)<<3) | ((c&0xF8)>>3))
#endif

#define COLOUR_CREAM			(COLOUR_24TO16(0xEEE7D0))
#define COLOUR_AQUA				(COLOUR_24TO16(0x00B7EB))
#define COLOUR_ORANGE			(COLOUR_24TO16(0xFF7F11))
#define COLOUR_BLUE_SEA_TINT	(COLOUR_24TO16(0x508DC5))		/* blue, but not too dark nor too bright. eg; Glass Lite:Volume */
#define COLOUR_GREEN_TINT		(COLOUR_24TO16(0x00FF1E))		/* softer green. used for highlighting */
#define COLOUR_PURPLE_GLOW		(COLOUR_24TO16(0xFF10CF))
#define COLOUR_GRAY				(COLOUR_24TO16(0x777777))
#define COLOUR_HOVER			(COLOUR_24TO16(0x28C672))
#define COLOUR_TASKBARFR		(COLOUR_24TO16(0x141414))
#define COLOUR_TASKBARBK		(COLOUR_24TO16(0xD4CAC8))
#define COLOUR_SOFTBLUE			(COLOUR_24TO16(0X7296D3))
#define COLOUR_PINK				(COLOUR_24TO16(RGB(248,184,128)))



enum _pal {
	COLOUR_PAL_BLACK,

	COLOUR_PAL_LIGHTGREY,
	COLOUR_PAL_LIGHTERGREY,
	COLOUR_PAL_DARKGREY,
	COLOUR_PAL_GREY,
	COLOUR_PAL_GRAY = COLOUR_PAL_GREY,
	
	COLOUR_PAL_DARKERGREEN,
	COLOUR_PAL_DARKGREEN,   
	COLOUR_PAL_LIGHTGREEN,
	COLOUR_PAL_BRIGHTGREEN,
	COLOUR_PAL_GREEN,
	COLOUR_PAL_GREENHUE,
		
	COLOUR_PAL_AQUA,
	COLOUR_PAL_PINK,
	
	COLOUR_PAL_HOVER,
	
	COLOUR_PAL_BLUE_SEA,
	COLOUR_PAL_SOFTBLUE,
	COLOUR_PAL_CYAN,
	COLOUR_PAL_BLUE,
	COLOUR_PAL_DARKBLUE,

	COLOUR_PAL_LDS,
	COLOUR_PAL_HEATH,
		
	COLOUR_PAL_HOMER,
	COLOUR_PAL_YELLOW,

	COLOUR_PAL_RED,
	COLOUR_PAL_REDISH,
	COLOUR_PAL_MAGENTA,
	COLOUR_PAL_REDFUZZ,
	
	COLOUR_PAL_ORANGE,

	COLOUR_PAL_DARKBROWN,
	COLOUR_PAL_DARKERBROWN,
	COLOUR_PAL_LIGHTBROWN,
	COLOUR_PAL_BROWN,

	COLOUR_PAL_BLUE_SEA_TINT,
	COLOUR_PAL_GREEN_TINT,
	COLOUR_PAL_PURPLE_GLOW,	
	COLOUR_PAL_TASKBARFR,
	COLOUR_PAL_TASKBARBK,

	COLOUR_PAL_WATER,

	COLOUR_PAL_CREAM,
	COLOUR_PAL_WHITE,

	COLOUR_PAL_MAROON,
	COLOUR_PAL_GOLD,
	
	COLOUR_PAL_PL08,
	COLOUR_PAL_PL09,
	COLOUR_PAL_PL0B,
	COLOUR_PAL_PL0D,
	COLOUR_PAL_PL0E,
	COLOUR_PAL_PL16,
	COLOUR_PAL_PL1A,

	COLOUR_PAL_PG_01,
	COLOUR_PAL_PG_02,
	COLOUR_PAL_PG_03,
	COLOUR_PAL_PG_04,
	COLOUR_PAL_PG_05,
	COLOUR_PAL_PG_06,
	COLOUR_PAL_PG_07,
	COLOUR_PAL_PG_08,
	COLOUR_PAL_PG_09,
	COLOUR_PAL_PG_0A,
	COLOUR_PAL_PG_0B,
	COLOUR_PAL_PG_0C,
	COLOUR_PAL_PG_0D,
	COLOUR_PAL_PG_0E,
	COLOUR_PAL_PG_11,
	COLOUR_PAL_PG_12,
	COLOUR_PAL_PG_13,
	COLOUR_PAL_PG_14,
	COLOUR_PAL_PG_15,
	COLOUR_PAL_PG_16,
	COLOUR_PAL_PG_17,
	COLOUR_PAL_PG_4F,
	COLOUR_PAL_PG_51,

	COLOUR_PAL_PLYEDGE,
	COLOUR_PAL_CHERRYBLOSSOM,


	COLOUR_PAL_BACKGROUND,
	COLOUR_PAL_Pitch,
	COLOUR_PAL_Meadow,
	COLOUR_PAL_Park,
	COLOUR_PAL_Residential,
	COLOUR_PAL_School,
	COLOUR_PAL_Industrail,
	COLOUR_PAL_Building,
	COLOUR_PAL_Parking,
	COLOUR_PAL_SportsCentre,
	COLOUR_PAL_Construction,
	COLOUR_PAL_Church,
	COLOUR_PAL_Administration,
	COLOUR_PAL_Playground,
	COLOUR_PAL_MixedForest,
	COLOUR_PAL_Cemetery,
	COLOUR_PAL_GolfCourse,
	COLOUR_PAL_MilArea,
	COLOUR_PAL_BrushScrub,
	COLOUR_PAL_Sand,
	COLOUR_PAL_MarshWetland,
	COLOUR_PAL_Dam,
	COLOUR_PAL_RetailArea,
	COLOUR_PAL_Hospital,
	COLOUR_PAL_Water,
	COLOUR_PAL_Sea,
	COLOUR_PAL_DeciduousForest,
	COLOUR_PAL_Stadium,
	COLOUR_PAL_AirfieldApron,
	COLOUR_PAL_AerodromeAirfield,
	COLOUR_PAL_Supermarket,
	COLOUR_PAL_Quarry,
	COLOUR_PAL_PowerStation,
	COLOUR_PAL_PedestrianArea,
	COLOUR_PAL_PlayingField,
	COLOUR_PAL_RailwayPlatform,
	COLOUR_PAL_Pier,
	COLOUR_PAL_Barracks,
	COLOUR_PAL_Zoo,
	
	
	COLOUR_PAL_Highway,
	COLOUR_PAL_Freeway,
	COLOUR_PAL_Road,
	COLOUR_PAL_ArterialRoad,
	COLOUR_PAL_PrincipledHighway,
	COLOUR_PAL_ResidentialStreet,
	COLOUR_PAL_CollectorRoad,
	COLOUR_PAL_ServiceRoad,
	COLOUR_PAL_LivingStreet,
	COLOUR_PAL_Roundabout,
	COLOUR_PAL_Path,
	COLOUR_PAL_CountryRoad,
	COLOUR_PAL_FootPath,
	COLOUR_PAL_ServiceRoadRestricted,
	COLOUR_PAL_Steps,
	COLOUR_PAL_Cycleway,
	COLOUR_PAL_AirportRunway,
	COLOUR_PAL_Mooring,


	COLOUR_PAL_TOTAL,
	PALETTE_TOTAL = COLOUR_PAL_TOTAL
};


void palette_init ();
uint16_t paletteGet (const uint8_t idx);



#endif


