

// feel the magic, this is not how i normally do thing.


//#include "vfont/fonts/astrology.h"
//#include "vfont/fonts/cursive.h"
//#include "vfont/fonts/cyrilc_1.h"
//#include "vfont/fonts/cyrillic.h"
#include "vfont/fonts/futural.h"
//#include "vfont/fonts/futuram.h"
//#include "vfont/fonts/gothgbt.h"
//#include "vfont/fonts/gothgrt.h"
//#include "vfont/fonts/gothiceng.h"
//#include "vfont/fonts/gothicger.h"
//#include "vfont/fonts/gothicita.h"
//#include "vfont/fonts/gothitt.h"
//#include "vfont/fonts/greek.h"
//#include "vfont/fonts/greekc.h"
//#include "vfont/fonts/greeks.h"
//#include "vfont/fonts/japanesea.h"
//#include "vfont/fonts/japaneseb.h"
//#include "vfont/fonts/markers.h"
//#include "vfont/fonts/mathlow.h"
//#include "vfont/fonts/mathupp.h"
//#include "vfont/fonts/meteorology.h"
//#include "vfont/fonts/music.h"
//#include "vfont/fonts/romans.h"
//#include "vfont/fonts/romand.h"
//#include "vfont/fonts/romant.h"
//#include "vfont/fonts/scriptc.h"
//#include "vfont/fonts/scripts.h"
//#include "vfont/fonts/symbolic.h"
//#include "vfont/fonts/timesg.h"
//#include "vfont/fonts/timesi.h"
//#include "vfont/fonts/timesib.h"
//#include "vfont/fonts/timesr.h"
//#include "vfont/fonts/timesrb.h"

